services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  grafana:
    image: grafana/grafana:latest
    ports:
      - "5000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: egonik
      GF_SECURITY_ADMIN_PASSWORD: HisPro10
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5455:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
